org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configureondemand=true

group=at.yedel
modName=Advantimations
modId=advantimations
modDescription=Client-side mod to cancel animations
modIcon=assets/advantimations/advantimations.png
version=2.1.2
versionType=STABLE
license=LGPL-3.0-only
modrinthId=c0aI2COX
modrinthLogoLink=https://cdn.modrinth.com/data/cached_images/86cf51c6826bdd5182f3e47ca16f1514f4c1fb79.png