org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
org.gradle.configureondemand=true

group=at.yedel
modName=faux
modId=faux
modDescription=Mutes mod loader dependencies
modIcon=assets/faux/faux.png
version=1.0.0
versionType=STABLE
license=LGPL-3.0-only
modrinthId=lDJcSaOT
modrinthLogoLink=https://cdn.modrinth.com/data/cached_images/fdac2d1968803e8a0bb323f9dbf005542fc8133f.png